### ISSUE TITLE
Visualization errors out - user count> hour wise

### ISSUE THREAD

**Issue by sarthak1996** [sarthak1996/Udacity-Python#11]
```
`               PS: Case sensitivity has been disabled!
::::::::::::::::::::::Phase: Data Visualization:::::::::::::::::::::::
===============Filtering data based on following params===============
**********************************************************************
*Included Cities: Test Data/chicago , Test Data/new York City , Test Data/washington*
*                     Included Months: Jan , Mar                     *
*                   Included Days: Mon , Tue , Wed                   *
*                 Visualization type: ['User Count']                 *
*                Visualization subtype: ['Hour wise']                *
**********************************************************************`
```

Error:

```
hour  day_in_month  month  Dependent  Unknown
0     8             9      1        1.0      0.0
1    17             8      1        0.0      1.0
Traceback (most recent call last):
  File "bikeshare_2.py", line 935, in <module>
    main()
  File "bikeshare_2.py", line 877, in main
    visualize_data(df.copy())
  File "bikeshare_2.py", line 798, in visualize_data
    visualize_user_counts_hour_wise(df)
  File "bikeshare_2.py", line 704, in visualize_user_counts_hour_wise
    hour, None, None, None, None, None, None
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 189, in __setitem__
    self._setitem_with_indexer(indexer, value)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 445, in _setitem_with_indexer
    raise ValueError("cannot set a row with "
ValueError: cannot set a row with mismatched columns
```

**Comment by sarthak1996** [comment]
Duplicate of #9
