### ISSUE TITLE
Error in stat calculation for washington

### ISSUE THREAD

**Issue by sarthak1996** [sarthak1996/Udacity-Python#13]
Washington does not have gender and birth year columns
Traceback (most recent call last):
  File "bikeshare_2.py", line 958, in <module>
    main()
  File "bikeshare_2.py", line 898, in main
    user_stats(df)
  File "bikeshare_2.py", line 497, in user_stats
    print(df['Gender'].value_counts().to_string())
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 2489, in _get_item_cache
    values = self._data.get(item)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Gender'

**Comment by sarthak1996** [comment]
Issue fixed via [Fix for Issue #13](https://github.com/sarthak1996/Udacity-Python-Bikeshare/commit/8c4ee8c6d0d49d43f796f8019615ec83fb848da6)

**Comment by sarthak1996** [comment]
Issue completely fixed after above fix
