### ISSUE TITLE
Error in visualization of user types vs hour

### ISSUE THREAD

**Issue by sarthak1996** [sarthak1996/Udacity-Python#6]
Traceback (most recent call last):
  File "bikeshare_2.py", line 907, in <module>
    main()
  File "bikeshare_2.py", line 849, in main
    visualize_data(df.copy())
  File "bikeshare_2.py", line 770, in visualize_data
    visualize_user_counts_hour_wise(df)
  File "bikeshare_2.py", line 688, in visualize_user_counts_hour_wise
    df_temp.sort_values('hour', inplace=True)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 4421, in sort_values
    stacklevel=stacklevel)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 1382, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'hour'

**Comment by sarthak1996** [comment]
Fix merged via [Issue #6 fix](https://github.com/sarthak1996/Udacity-Python-Bikeshare/commit/fd670e33415427b53f87c71926f1e9d651589202)
