### ISSUE TITLE
Visualization error if key does not exist.

### ISSUE THREAD

**Issue by sarthak1996** [sarthak1996/Udacity-Python#8]
If Customer or dependent or subscriber does not exists, then visualization is erroring out with:
```
               PS: Case sensitivity has been disabled!
::::::::::::::::::::::Phase: Data Visualization:::::::::::::::::::::::
===============Filtering data based on following params===============
**********************************************************************
*Included Cities: Test Data/chicago , Test Data/new York City , Test Data/washington*
*                     Included Months: Jan , Mar                     *
*                   Included Days: Mon , Wed , Tue                   *
*                 Visualization type: ['User Type']                  *
*                     Visualization subtype: []                      *
**********************************************************************
```

```
Traceback (most recent call last):
  File "bikeshare_2.py", line 909, in <module>
    main()
  File "bikeshare_2.py", line 851, in main
    visualize_data(df.copy())
  File "bikeshare_2.py", line 791, in visualize_data
    visualize_user_types_in_city(df)
  File "bikeshare_2.py", line 579, in visualize_user_types_in_city
    df_temp['Customer'].values, df_temp['Dependent'].values,
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 2489, in _get_item_cache
    values = self._data.get(item)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Customer'
```

Visualizing > 2.

**Comment by sarthak1996** [comment]
Exists for all the visualization..

**Comment by sarthak1996** [comment]
To check if fix of [Fix of Issue #8](https://github.com/sarthak1996/Udacity-Python-Bikeshare/commit/32e0ef37f7ca95de36278c7c845ff8cd434682b1) resolved the issue.. and check for regression

**Comment by sarthak1996** [comment]
Initial look: looks likes the issues is resolved.. rigorous testing reqd..check for regression.

**Comment by sarthak1996** [comment]
No errors on test data.

**Comment by sarthak1996** [comment]
Issue fixed. Refer https://github.com/sarthak1996/Udacity-Python-Bikeshare/issues/8#issuecomment-440036201
