### ISSUE TITLE
Mismatch when inserting blank rows in df for visualization

### ISSUE THREAD

**Issue by sarthak1996** [sarthak1996/Udacity-Python#9]
When default rows are inserted eg. monday not present in data then default monday row would be populated for visualization.

This gives error:
Traceback (most recent call last):
  File "bikeshare_2.py", line 909, in <module>
    main()
  File "bikeshare_2.py", line 851, in main
    visualize_data(df.copy())
  File "bikeshare_2.py", line 766, in visualize_data
    visualize_user_counts_day_wise(df)
  File "bikeshare_2.py", line 618, in visualize_user_counts_day_wise
    day, None, None, i, None, None, None
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 189, in __setitem__
    self._setitem_with_indexer(indexer, value)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 445, in _setitem_with_indexer
    raise ValueError("cannot set a row with "
ValueError: cannot set a row with mismatched columns

**Comment by sarthak1996** [comment]
Check if issue is resolved by fix of #8

**Comment by sarthak1996** [comment]
Check if the above fix resolved the issue

**Comment by sarthak1996** [comment]
Error persists:
```
               PS: Case sensitivity has been disabled!
::::::::::::::::::::::Phase: Data Visualization:::::::::::::::::::::::
===============Filtering data based on following params===============
**********************************************************************
*Included Cities: Test Data/chicago , Test Data/new York City , Test Data/washington*
*                     Included Months: Jan , Mar                     *
*                   Included Days: Mon , Tue , Wed                   *
*                 Visualization type: ['User Count']                 *
*               Visualization subtype: ['Month wise']                *
**********************************************************************
```

Error
```
Traceback (most recent call last):
  File "bikeshare_2.py", line 932, in <module>
    main()
  File "bikeshare_2.py", line 874, in main
    visualize_data(df.copy())
  File "bikeshare_2.py", line 783, in visualize_data
    visualize_user_counts_month_wise(df)
  File "bikeshare_2.py", line 657, in visualize_user_counts_month_wise
    df_temp.loc[df_temp.shape[0]] = [month + 1, None, None, None]
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 189, in __setitem__
    self._setitem_with_indexer(indexer, value)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 445, in _setitem_with_indexer
    raise ValueError("cannot set a row with "
ValueError: cannot set a row with mismatched columns
```

**Comment by sarthak1996** [comment]
Only month giving error on above filters, all the rest are working fine.

**Comment by sarthak1996** [comment]
Check if [Fix](https://github.com/sarthak1996/Udacity-Python-Bikeshare/commit/caec0c590ea7901887b097ad4782fda38f11a6bd) resolved the issue

**Comment by sarthak1996** [comment]
Initial look: Looks like issue is resolved.. need to do rigurous testing and check for regression..

**Comment by sarthak1996** [comment]
No errors on test data.

**Comment by sarthak1996** [comment]
Issue fixed. refer: https://github.com/sarthak1996/Udacity-Python-Bikeshare/issues/9#issuecomment-440044097
